version: "3.8"

services:
  # -----------------------------------------------------------------
  # SERVICE 1: AUTH (Port 3001)
  # -----------------------------------------------------------------
  auth-service:
    container_name: mecca_auth
    build: ./Mecca-auth-service
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./Mecca-auth-service/.env
    environment:
      - PORT=3001
      # - DB_HOST=host.docker.internal  # <--- INI KUNCINYA

    networks:
      - mecca-network

  # -----------------------------------------------------------------
  # SERVICE 2: ADMIN (Port 3002)
  # -----------------------------------------------------------------
  admin-service:
    container_name: mecca_admin
    build: ./Mecca-admin-service
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - ./Mecca-admin-service/.env
    environment:
      - PORT=3002
      # - DB_HOST=host.docker.internal  # <--- INI KUNCINYA
    depends_on:
      - auth-service
    networks:
      - mecca-network

  # -----------------------------------------------------------------
  # SERVICE 3: STUDENT (Port 3003)
  # -----------------------------------------------------------------
  student-service:
    container_name: mecca_student
    build: ./Mecca-student-service
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - ./Mecca-student-service/.env
    environment:
      - PORT=3003
      # - DB_HOST=host.docker.internal  # <--- INI KUNCINYA
    depends_on:
      - auth-service
    networks:
      - mecca-network

  # -----------------------------------------------------------------
  # SERVICE 4: TEACHER (Port 3004)
  # -----------------------------------------------------------------
  teacher-service:
    container_name: mecca_teacher
    build: ./Mecca-teacher-service
    restart: always
    ports:
      - "3004:3004"
    env_file:
      - ./Mecca-teacher-service/.env
    environment:
      - PORT=3004
      # - DB_HOST=host.docker.internal  # <--- INI KUNCINYA
    depends_on:
      - auth-service
    networks:
      - mecca-network

  # -----------------------------------------------------------------
  # SERVICE 5: PARENT (Port 3005)
  # -----------------------------------------------------------------
  parent-service:
    container_name: mecca_parent
    build: ./Mecca-parent-service
    restart: always
    ports:
      - "3005:3005"
    env_file:
      - ./Mecca-parent-service/.env
    environment:
      - PORT=3005
      # - DB_HOST=host.docker.internal  # <--- INI KUNCINYA
    depends_on:
      - auth-service
    networks:
      - mecca-network

networks:
  mecca-network:
    driver: bridge